message: Ola git
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:sqlite:MyMusic.db
    username: ""
    password: ""
    driver-class-name:  org.sqlite.JDBC
    database-platform: com.dojo.musicas.config.SQLiteDialect
